sudo: required
services:
  - docker

before_install:
  - docker build -t tasfeqhub/docker-react-app -f Dockerfile.dev .
 
script:
  - docker run -e CI=true tasfeqhub/docker-react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-eu-west-1-194615496736"
  bucket_path: "docker-react-app"
  on:
    branch: master  
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
                    